pj3_django/config2/books/urls.py
from django.urls import path, include
from . import views

app_name = 'books'
urlpatterns = [
    # http://127.0.0.1:8000/books/->
    path('', views.BooksIndexView.as_view(), name='index'), 

    # http://127.0.0.1:8000/books/book ->
    path('book/', views.BookList.as_view(), name='booklist'),   

    # http://127.0.0.1:8000/books/publisher ->
    path('publisher/', views.PublisherList.as_view(), name='publisherlist'), 

    # http://127.0.0.1:8000/books/publisher/1 ->
    path('publisher/<int:pk>/', views.PublisherDetail.as_view(), name='publisherdetail'),   

    # http://127.0.0.1:8000/books/publisher/insert->
    path('publisher/insert/', views.PublisherCreate.as_view(), name='publisherinsert'),

    # http://127.0.0.1:8000/books/publisher/update/2->
    path('publisher/update/<int:pk>/', views.PublisherUpdate.as_view(), name='publisherupdate'),

    # http://127.0.0.1:8000/books/publisher/delete/2->
    path('publisher/delete/<int:pk>/', views.PublisherDelete.as_view(), name='publisherdelete'),


]

# as_view() 메소드 - 진입메소드, 
# urls.py에서 클래스형뷰의 as_view() 메소드를 호출

pj3_django/config2/books/models.py
from django.db import models

class Publisher(models.Model):
    name = models.CharField(max_length=50)
    addr = models.CharField(max_length=100)
    website = models.CharField(max_length=50)
    photo = models.ImageField(upload_to='photos/%Y', default='photos/no.png')
    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField("Author")
    publisher = models.ForeignKey('Publisher', on_delete = models.CASCADE)
    pubdate = models.DateField()
    def __str__(self):
        return self.title

class Author(models.Model):
    name = models.CharField(max_length=50)
    intro = models.CharField(max_length=100)
    email = models.EmailField()
    def __str__(self):
        return self.name

pj3_django/config2/books/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Book, Publisher, Author
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import redirect

class BookList(ListView):
    model = Book

class PublisherList(ListView):
    model = Publisher
    
class PublisherDetail(DetailView):
    model = Publisher

class PublisherCreate(CreateView):
    model = Publisher
    fields = ['name', 'addr', 'website', 'photo']   # 입력 받을 컬럼 지정
    template_name = 'books/publisherinsert.html'
    success_url = '/books'  # CreateView, UpdateView, DeleteView 를 사용시 특정기능 수행후 페이지 이동
    # def form_valid(self, form):
    #     print(form.instance.name)
    #     print(form.instance.addr)
    #     print(form.instance.photo)
    #     if form.is_valid():
    #         form.instance.save()
    #         return redirect('/books/publisher')
    #     else:
    #         return self.render_to_response({'form':form})

class PublisherUpdate(UpdateView):
    model = Publisher
    fields = ['name', 'addr', 'website', 'photo']   # 수정할 컬럼 지정
    template_name = 'books/publisherupdate.html'
    success_url = '/books/publisher'

class PublisherDelete(DeleteView):
    model = Publisher
    template_name = 'books/publisherdelete.html'
    success_url = '/books/publisher'

class BooksIndexView(TemplateView):
    template_name = 'books/index.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['mlist'] = ['book', 'publisher', 'author']
        return context

pj3_django/config2/books/templates/books/book_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>books/book_list.html</h1>
    <hr>
    <ul>
    {% for b in object_list%}
        <li>{{b.title}} - {{b.publisher}}</li>
    {% endfor %}
    </ul>
</body>
</html>

pj3_django/config2/books/templates/books/index.html
{% extends 'base_books.html' %}
{% block content %}

<h1>books/index.html</h1>
<hr>
<ul>
    {% for m in mlist %}
    <li><a href="/books/{{m}}">{{m}}</a></li>
    {% endfor %}
</ul>

{% endblock %}

pj3_django/config2/books/templates/books/publisher_detail.html
{% extends 'base_books.html' %}
{% block content %}
    <h1>books/publisher_detail.html</h1>
    <hr>
    <p>출판사명 : {{object.name}}</p>
    <p>위치 : {{object.addr}}</p>
    <p>홈페이지 : {{object.website}}</p>
    <p>전경사진 : <img src="{{object.photo.url}}">{{object.photo.url}}</p> <!-- 이미지 주소 출력 -->
    <hr>
    <!-- <a href="/books/publisher">출판사 목록</a> -->
    <a href="{% url 'books:publisherlist' %}">출판사 목록</a>
    <a href="{% url 'books:publisherupdate' pk=object.id%}">수정하기</a>
    <a href="{% url 'books:publisherdelete' pk=object.id%}">삭제하기</a>
{% endblock %}

pj3_django/config2/books/templates/books/publisher_list.html
{%extends 'base_books.html'%}
{%block content%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>books/publisher_list.html</h1>
    <hr>
    <ul>
        {% for p in object_list%}
            <li><a href="{%url 'books:publisherdetail' p.id %}">{{p.name}}</a> - {{p.addr}}</li>
        {% endfor %}
    </ul>
    <hr>
    <a href="{% url 'books:index' %}">홈으로</a>
    <a href="{% url 'books:publisherinsert' %}">출판사 등록</a>
    
</body>
</html>
{% endblock %}

pj3_django/config2/books/templates/books/publisherdelete.html
{% extends 'base_books.html' %}
{% block content %}
    <h1>books/publisherdelete.html</h1>
    <hr>
    <p>출판사명: {{ object.name }}</p>
    <p>주 소: {{ object.addr }}</p>
    <p>홈페이지: {{ object.website }}</p>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="삭제하기">
    </form>
{% endblock %}

pj3_django/config2/books/templates/books/publisherinsert.html
{% extends 'base_books.html' %}
{% block content %}
    <h1>books/publisherinsert.html</h1>
    <hr>
    <!-- {{form.as_p}} -->
    <!-- {{form.as_ul}} -->
    <form id="frm1" method="POST" enctype="multipart/form-data">
        {%csrf_token%}
        <table border="1">
        {{form.as_table}}
        <tr>
            <td colspan="2"><input type="submit" value="등록"></td>
        </tr>
        </table>
    </form>
{% endblock %}

pj3_django/config2/books/templates/books/publisherupdate.html
{% extends 'base_books.html' %}
{% block content %}
    <h1>books/publisherupdate.html</h1>
    <hr>
    <table>
    <form method="post" id="frm1" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_table }}
        <tr>
            <td colspan="2"><input type="submit" value="수정하기"></td>
        </tr>
        </table>
    </form>
{% endblock %}