pj3_django/config/polls/urls.py
from django.urls import path, include
from . import views
app_name = 'polls'
urlpatterns = [
    # path(url패턴, url이 매칭되면 호출되는 뷰함수 [, 이름]),
    path('', views.index, name='list'),                   # http://127.0.0.1:8000/polls       
    path('<int:qid>/', views.detail, name='detail'),      # http://127.0.0.1:8000/polls       
    path('vote/<int:qid>/', views.vote, name='vote1'),    # http://127.0.0.1:8000/polls/vote/3 
    # => polls:vote1 으로 표기 {% url 'polls:vote1'%} 태그 사용
    path('dbtest/', views.dbtest),                        # http://127.0.0.1:8000/polls/dbtest       
]

pj3_django/config/polls/models.py
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField()
    def __str__(self):      # = 자바의 toString() 
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self): 
        return self.choice_text

pj3_django/config/polls/views.py
from django.shortcuts import render
from .models import Question
from django.shortcuts import get_object_or_404

def detail(request, qid):
    # q = Question.objects.get(id=qid)       # select * from question where id=qid
    q = get_object_or_404(Question, id=qid)  # err 발생시 404 페이지 출력
    c = q.choice_set.all()
    print(c, len(c), '*********************************')
    msg = {}
    msg['q'] = q
    if len(c) < 1:
        msg['err'] = '선택할 항목이 없습니다.'

    return render(request,'polls/detail.html', msg)

def index(request):
    qlist = Question.objects.all()
    return render(request, 'polls/index.html', {'qlist':qlist})    # 요청, 반환할 페이지

def vote(request, qid):
    q = Question.objects.get(id=qid)
    cid = request.POST['choice']
    # Question과 Choice는 1:N 관계, 외래키로 연결된 경우 모델 소문자_set 속성이 제공
    # q.choice_set.all()  # 모든 데이터 가져오기
    c = q.choice_set.get(id=cid)    # 특정 데이터 가져오기
    c.votes = c.votes + 1
    c.save()
    return render(request, 'polls/result.html', {'q':q})    # 요청, 반환할 페이지




def dbtest(request):    # 127.0.0.1:8000/polls/dbtest
    # -> id 값 없는경우 : 삽입
    # q = Question(question_text='좋아하는 운동은', pub_date='2021-01-07')
    # q.save()  
    # -> id 값 있는경우 : 해당 아이디 수정
    # q = Question(id=1, question_text='좋아하는 칼라는', pub_date='2021-01-07')
    # q.save()

    # 2) 조회
    # qlist = Question.objects.all()      # 모든 데이터
    # qlist = Question.objects.get(id=3)  # 조건에 맞는 데이터
    # print(qlist)

    # return render(request, 'polls/dbtest.html')   
    # return render(request, 'polls/dbtest.html', {'aa':'bb'})
    # return render(request, 'polls/dbtest.html', {'qlist':qlist})

    # 3) 삭제
    # q= Question.objects.get(id=1)   # 해당데이터를 가져온 뒤
    # q.delete()
    qlist = Question.objects.all()
    return render(request, 'polls/dbtest.html', {'qlist':qlist})

pj3_django/config/polls/templates/polls/dbtest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>dbtest.html</h2>
    <!-- <hr> -->
    <!-- <h3>{{qlist}}</h3>     변수의 값 출력시 -->
    <hr>
    {% if qlist %}
    <ul>
    {% for q in qlist %}
        <li>{{q.id}} - {{q.question_text}}</li>
    {% endfor %}
    </ul>
    {% else %}
    <p>자료없음</p>
    {% endif %}

</body>
</html>

pj3_django/config/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="/static/spring.css"/>
</head>
<body>
    <h1>detail.html</h1>
    <hr>
    <h3>{{q.question_text}}--{{q.pup_date}}</h3>
    <!--Question 과 Choice 는 1:N관계, 외래키로 연결된 경우 모델소문자_set속성이 제공됨-->
    <!--즉, q.choice_set.all() 단 템플릿 문법상 () 생략-->
    {% if err %}
    <h3>{{err}}</h3>
    {% else %}
    <form method="post" action="{%url 'polls:vote1' q.id%}">
        {%csrf_token%}
        {%for c in q.choice_set.all%}
            <input type="radio" name="choice" value="{{c.id}}">{{c.choice_text}}<br>
        {%endfor%}
        <input type="submit" value="투표하기">
    </form>
    {% endif %}
</body>
</html>

pj3_django/config/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="/static/spring.css"/>
</head>
<body>
    <h1>index.html</h1>
    <hr>
    {%if qlist%}
    <ul>
        {%for q in qlist%}
        <!--http://127.0.0.1:8000/polls/2-->
            <li><a href="/polls/{{q.id}}">{{q.id}} - {{q.question_text}}</a></li>
        {%endfor%}
    </ul>
    {%else%}
        <p>자료없음</p>
    {%endif%}
</body>
</html>

pj3_django/config/polls/templates/polls/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>result.html</h1>
    <hr>
    <h3>{{q.question_text}}</h3>
    <ul>
        {%for c in q.choice_set.all%}
        <li>{{c.choice_text}} -- {{c.votes}}</li>
        {%endfor%}
    </ul>
    <hr>
    <a href="{%url 'polls:list' %}">목록으로</a>
</body>
</html>